spring:
  application:
    name: "location-management-service"
  jpa:
    show-sql: true
    properties:
        hibernate:
          dialact: "org.hibernate.dialect.MySQL8Dialect"
          format_sql: true
#    hibernate:
#      ddl-auto: create
  datasource:
    url: "jdbc:mysql://localhost:3306/hotel-reservation?useSSL=false&serverTimezone=UTC"
    username: root
    password: pass
    driverClassName: "com.mysql.cj.jdbc.Driver"
server:
  port: 8084
